name: "action-swit"
description: "Send Message to Swit"
author: "roharon"

inputs:
  webhooks_url:
    description: "Your Swit app's webhooks url"
    required: true
  message:
    description: "Message that you want"
    default: "🏷 ${{ job.status }} ${{ github.sha }} - by ${{ github.actor }}"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  color: "orange"
  icon: "send"
