name: Publish Docker Image
on:
  push:
    branches:
      - master
    tags:
      - v1

jobs:
  publish_image:
    name: Publish Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Github Action for Swit
      uses: roharon/action-swit@v1
      with:
        webhooks_url: ${{ secrets.WEBHOOKS_URL}}
